# vim: set ft=yaml ts=2 expandtab:
---

mariadb_server_cnf_main: /etc/my.cnf
mariadb_server_cnf: /etc/my.cnf.d/mariadb-server.cnf
mariadb_daemon: mariadb
mariadb_default_stream: '10.5'
mariadb_server_packages:
- mariadb-server
- python3-PyMySQL
mariadb_logrotate: /etc/logrotate.d/mariadb
mariadb_socket: /var/lib/mysql/mysql.sock

...
