# vim: set ft=yaml ts=2 expandtab:
---

- name: dependencies
  hosts: ci

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: mafalb.mariadb.server

...
