# vim: set ft=yaml ts=2 expandtab:
---

- name: dependencies
  hosts: all

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  pre_tasks:

  # https://github.com/geerlingguy/ansible-role-composer/issues/54
  #
  - name: get status of systemd-tmpfiles-setup.service # noqa 301 303
    when: ansible_service_mgr == 'systemd'
    changed_when: false
    command: systemctl status systemd-tmpfiles-setup.service

  roles:

  - role: mafalb.mariadb.server

...
