# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:

  - name: t_centos7
    image: centos:7
    command: /usr/sbin/init
    volume_mounts:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - "/tmp/gugu:/run"
    capabilities:
    - SYS_ADMIN
    tmpfs:
    - /run
    - /run/lock

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
