# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify key and csr
  hosts: ci

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - name: get info from the mysql instance
    mysql_info:
      login_user: root
      filter: version
    register: _mariadb_info

  - name: debug
    debug:
      var: _mariadb_info

...
